pipelines:
  default:
    - step:
        name: Build elkog + tests and examples
        image: ubuntu:22.04
        script:
          - apt-get update
          - DEBIAN_FRONTEND=noninteractive apt-get install -qq --no-install-recommends make g++ cmake git ca-certificates ssh

          # Rewrite the relative submodule url as bitbucket doesn't handle relative paths correctly
          - sed -i 's/url = \.\.\(.*\)/url = git@bitbucket.org:$BITBUCKET_TEAM\1/g' .gitmodules
          - git submodule update --init --recursive

          - mkdir build
          - cd build
          - cmake .. -DCMAKE_BUILD_TYPE=Debug
          - make elklog
          - make elklog_example
          - make static_example
          - make unit_tests
          - test/unit_tests